### ISSUE TITLE
More Templates for HTML, PDF possible?

### ISSUE THREAD

**Issue by aviadavi** [nknapp/bootprint-swagger#1]
Hi.

Do you have more handlebars templates for bootprint swagger (there is only 1 correct me if i'm wrong) ?

Is generating PDF possible ?

**Comment by nknapp** [comment]
At the moment, there is only this one template for swagger. Although I consider it usable at the moment (we used it to provide documentation to our customers) it can certainly be improved. So if you have any improvements, feel free to create an issue with more detailed ideas or a PR. I'm going to add a section about "contributing" to the documentation soon.

PDF generation is a bit tricky and it is a more general question of converting HTML to PDF. I've tried the following:

1) [PhantomJS](http://phantomjs.org/) with [the rasterize script](https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js) - Works at the first glance, but it does not add PDF bookmarks and the links within the document are not working
2) [WeasyPrint](http://weasyprint.org/) - Looks good and generates PDF-bookmarks. PDF-generation takes a bit longer. Links within the document are not working.
3) [wkhtmltopdf](http://wkhtmltopdf.org/) - Takes really long to generate PDF. The resulting file is huge (2,3 MB for the petstore-example). Links and PDF-bookmarks are working fine. 
4) [PrinceXML](http://www.princexml.com) - Runs very quickly, small PDF, links are working, layout looks good. It's a great tool, but I can't justify $3800 just for sending a nice Rest-API-Reference as PDF instead of HTML. I would use it for open source projects though (for which it is free).

Since every option had a large drawback (links not working, file size, price), we just sent a zip-file containing the HTML- and the StyleSheets.
It's not what I had intended to do with Bootprint in the beginning, but at the moment I do not see another option.

**Comment by aviadavi** [comment]
The idea is that the HTML will contain the following:
1) Default Values
2) Min/Max Value
3) Pattern 
4) Examples

**Comment by nknapp** [comment]
Most of these values belong into the [bootprint-json-schema](https://github.com/nknapp/bootprint-json-schema) module. I would like to encourage you to clone the repository, make your changes and submit a pull request. If you need a starting point. From what I can see, *default values*, *min/max* and *pattern* belong into [the json-schema/datatype](https://github.com/nknapp/bootprint-json-schema/blob/master/handlebars/partials/json-schema/datatype.hbs) partial, which already renders the "format" and "enum"-values.

"Examples" in the json-schema parts of the swagger-spec would also go into `bootprint-json-schema` and there into the partial [json-schema/body](https://github.com/nknapp/bootprint-json-schema/blob/master/handlebars/partials/json-schema/body.hbs) probably below the description. Pretty printed JSON can be rendered with the `{{json value}}`-helper.

"Examples" in the swagger-parts of the spec only seem to be possible within response definitions, which  would go into the partials of this ("bootprint-swagger") module, namely [swagger/responses](https://github.com/nknapp/bootprint-swagger/blob/master/handlebars/partials/swagger/responses.hbs).

I may find some time to add these values myself, but a pull-request would probably be accepted faster than that.

I am currently working on documentation for the template-modules. Or better, I am trying to figure out a good way to generate good documentation partly from inline comments within partials, less-files and js-files.

**Comment by JamesPaden** [comment]
@nknapp late to the party, but you might consider https://docraptor.com for HTML to PDF. It uses PrinceXML on the backend, but has a saas-based pricing model.

**Comment by nknapp** [comment]
@aviadavi can you provide a simple (possibly minimal) example containing the data you'd like to see in the output? That would be a great help.

**Comment by nknapp** [comment]
@JamesPaden I don't think a SaaS is the right alternative for my purposes, but it might be for others, thanks for the hint.

**Comment by nknapp** [comment]
I've included "default-values" and examples in the JSON-Schema into the current version.

**Comment by nknapp** [comment]
I've extracted the two remaining TODOs into separate issues. This issue will now be closed
