### ISSUE TITLE
Question about using custom partials

### ISSUE THREAD

**Issue by tstatler** [nknapp/bootprint-swagger#34]
I'm having problems getting my custom partials to render. I'm using bootprint 0.7.3 with the swagger module. I have a config file (config.js) with the following content:

```
module.exports = {
    "handlebars": {
        "partials": "/full/path/to/partials"
    }
}
```

The specified `partials` directory contains the following:

```
partials
└──swagger
    └──paths.hbs
```

`paths.hbs` is a copy of the original partial with changes I addded.

I pass the config file as a parameter to `bootprint`:

```
bootprint -f config.js swagger swagger-schema/continuum-api.json out
```

Result: 
HTML is built correctly but without the changes in my custom partials.

Expected: 
HTML includes changes in custom partial.

Any idea what I'm missing?

**Comment by nknapp** [comment]
At the first glance, there is nothing wrong with your setup. 
Can you clone the [bootprint-examples](https://github.com/nknapp/bootprint-examples) and try whether the `config-file` example is working for you?

**Comment by tstatler** [comment]
Thanks very much, I was able to get things working by looking at the example.

**Comment by nknapp** [comment]
Great. Just out of interest: Are you still playing with bootprint or are you using it in production. I would like to know, because you are the first one who contacts me about overriding partials and such. 
As long as everybody just uses bootprint-swagger to render their docs, I can still make breaking changes to the templates. But if you rely on me not changing the name or structure of partials, I will be more cautious from now on. If you're not comfortable telling me here in the public, you can also send me an e-mail. However,  I would really like to have this feedback.

Also, if you have a suggestion for a feature or something that would have helped you, please let me know (preferably in a new issue) 

(It 00:15, I'm just submitting this now. Forgive any spelling errors...)

**Comment by tstatler** [comment]
I'm still evaluating different doc generators for our project, but I think bootprint is a great approach. I guess I'm not entirely sure what types of issues might arise, but it would be frustrating if custom partials I made broke due to upstream changes. 

Anyway, great tool, thanks for putting it together!
