### ISSUE TITLE
Does not work at all for me

### ISSUE THREAD

**Issue by guidoffm** [nknapp/bootprint-swagger#42]
1st problem: After installing bootprint and bootprint swagger when I start bootprint I get a message complaining about missing "handelbars". There might be a missing dependency to handlebars. After installing handlebars I these versions:

├─┬ bootprint@0.7.7
│ └─┬ customize-engine-handlebars@0.5.2
│   └── handlebars@3.0.3
├── bootprint-swagger@0.11.0
├─┬ bower@1.5.1
│ └── handlebars@2.0.0
└── handlebars@4.0.3
After calling 
bootprint swagger http://localhost:53108/backend/swagger/docs/v1 neu
I get:

Loading bootprint-swagger 0.11.0
Loading bootprint-json-schema 0.8.1
Loading bootprint-base 0.6.1
[object Object]

No output is generated at all.

**Comment by nknapp** [comment]
Hi @guidoffm, thanks for taking the time to report this.
I have unpublished `bootprint-base@0.6.1`. The latest changes seem to be broken. I've tested this with the petstore-example and it seems to work. I'll investigate further tonight.
Mind trying again?

**Comment by guidoffm** [comment]
Hi Nils,

the issue with missing handlebars dependency is gone. npm ls -g now reads:
├─┬ bootprint@0.7.7
│ └─┬ customize-engine-handlebars@0.5.2
│   └── handlebars@3.0.3
├─┬ bootprint-swagger@0.11.0
│ └─┬ bootprint-json-schema@0.8.1
│   └─┬ bootprint-base@0.6.0
│     └── handlebars@3.0.3
└─┬ bower@1.5.1
  └── handlebars@2.0.0

After calling
bootprint swagger http://localhost:53108/backend/swagger/docs/v1 neu
I get:

Loading bootprint-swagger 0.11.0
Loading bootprint-json-schema 0.8.1
Loading bootprint-base 0.6.0
[object Object]

Still no output generated at all.

**Comment by nknapp** [comment]
Can you try the petstore-example: `bootprint swagger http://petstore.swagger.io/v2/swagger.json target`.

**Comment by nknapp** [comment]
@guidoffm I have published the modules again tonight, I tried 
```bash
npm -g install bootprint
npm -g install bootprint-swagger

bootprint --version # prints "0.7.7"
bootprint swagger http://petstore.swagger.io/v2/swagger.json target
```
and I get the following result.
```
Loading bootprint-swagger 0.11.1
Loading bootprint-json-schema 0.8.3
Loading bootprint-base 0.6.2
[ 'target/index.html', 'target/main.css', 'target/main.css.map' ]
```
The `target/index.html`-file looks good. I would like to verify this with your setup, because I don't understand why your `bootprint`-call prints `[object Object]`. But since I cannot reproduce your situation (because I don't have access to your  `swagger.json`), I would like you to reproduce mine.

Could you try the new modules with your own swagger.json, but also with the petstore-example?

**Comment by jneubeck** [comment]
After uninstalling everything and reinstalling I get the following error

```
bootprint swagger http://petstore.swagger.io/v2/swagger.json target
Loading bootprint-swagger 0.11.1
Loading bootprint-json-schema 0.8.3
Loading bootprint-base 0.6.2

C:\Users\XXXX\AppData\Roaming\npm\node_modules\bootprint\node_modules\q\q.js:155
                throw e;
                ^
Error: The partial base/title could not be found
    at Object.invokePartial (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\bootprint\node_modules\customize-engine-handlebars\node_modules\handlebars\dist\cjs\handlebars\runtime.js:216:11)
    at Object.invokePartialWrapper [as invokePartial] (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\bootprint\node_modules\customize-engine-handlebars\node_modules\handlebars\dist\cjs\handlebars\runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\bootprint\node_modules\customize-engine-handlebars\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:221:23), <anonymous>:6:23)....
```

**Comment by nknapp** [comment]
@jneubeck Firstly I have to apologize for the long installing time of `bootprint-swagger`. npm@1 and npm@2 download all peer-dependencies, so the `bootprint` package has been downloaded three times. I have removed the dependency for now. 
The bug you observe is a regression that was introduced in `bootprint@0.7.4`. The partials are not registered correctly because Windows separates path-components with a backslash and not a slash.
I will fix that in a moment.

**Comment by nknapp** [comment]
@jneubeck I have released a new version of [customize](https://github.com/nknapp/customize) which is responsible for building the file-paths. 
Would you mind trying again? The just make sure that `npm ls -g` show `customize@0.5.0`, otherwise you won't have the fix installed.

**Comment by jneubeck** [comment]
Thank you it now works.

**Comment by nknapp** [comment]
Glad to hear
