### ISSUE TITLE
Support for YAML

### ISSUE THREAD

**Issue by etzlers** [nknapp/bootprint-swagger#45]
Is YAML supported by this project? If so I am having issues getting my model definitions to be included in the generated html page.

I just saw #15 which was moved to an issue in bootprint core.  Should I be addressing my issue there instead?

**Comment by nknapp** [comment]
YAML is supported since [bootprint 0.8.0](https://github.com/nknapp/bootprint/blob/master/CHANGELOG.md#v080---2015-11-23).
It's a bootprint issue, because this project only comtains the handlebars-template and less-file for rendering swagger-specs. Calling Handlebars and Less, and also loading the input, is the responsibility of the  `bootprint`-module. @stephank created a PR for YAML-support there.
The website http://bootprint.knappi.org still has another JSON-validation check so it does not have YAML support yet, but I intend to fix that when I have some more time.

**Comment by nknapp** [comment]
http://bootprint.knappi.org now also supports YAML.

**Comment by etzlers** [comment]
Thanks! :)
